image: node:16

cache:
  paths:
    - node_modules/
    - .cache/
    - public/

stages:
  - deploy

deploy:
  only: [ master ]
  stage: deploy
  script: make surge
  environment:
    name: surge
    url: https://${SURGE_DOMAIN}
