sidebar:
  link:
    home: /
    repo: https://github.com/albero-azure/albero/issues
    share: /
    contact: /


filter:
  platforms:
    - Azure

  technologies:
    - General
    - Analytics
    - Caching
    - Data Lake
    - IoT
    - MySQL
    - NoSQL
    - PostgreSQL
    - SQL Server / Database
    - Spark
    - Streaming
    - Time-Series

  viewpoints:
    - General
    - Security
    - Developer
    - Industry
    - Migration

mainpage:
  groups:
    - name: Main Decision Trees
      services:
        - name: Azure Data Services
          description: This is the main Decision Tree focused on selecting proper data backend technology on Azure.
          preview: /services/azure/mainDT_2.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
          filter:
            platforms:
              - Azure
            viewpoints:
              - General
            technologies:
              - General
              - Analytics
              - Time-Series

        - name: Azure Data Dev View
          description: This Decision Tree is focused on languages, file formats, SDKs and limitations of Azure Data Services.
          preview: /services/azure/DTAzureDev.png
          items:
            - /services/azure/dev.html
          filter:
            platforms:
              - Azure
            viewpoints:
              - Developer
            technologies:
              - General

        - name: Azure Data Security
          description: This is a Decision Tree focused on Security aspects, such as Priviliges, Networking and Encryption.
          preview: /services/azure/DTAzureSecurity.png
          items:
            - /services/azure/security.html
          filter:
            platforms:
              - Azure
            viewpoints:
              - Security
            technologies:
              - General

    - name: Technology-Focused Decision Trees
      services:
        - name: Azure Synapse and Azure Databricks
          description: In this decision tree we are trying to address a question - when to choose Synapse or Databricks.
          preview: /services/azure/DTSynapseDatabricks.png
          items:
            - /services/azure/sdbx.html
          filter:
            platform:
              - Azure
            viewpoints:
              - General
            technologies:
              - Analytics

        - name: SQL Database on Azure
          description: Here you can find the guidance on various service tiers for SQL Database on Azure.
          preview: /services/azure/DTAzureSQL.png
          items:
            - /services/azure/azuresql.html
          filter:
            platform:
              - Azure
            viewpoints:
              - General
            technologies:
              - SQL Server / Database

        - name: Streaming on Azure
          description: On this diagram you can find all the possible options to handle real-time data streaming and processing.
          preview: /services/azure/DTStreaming.png
          items:
            - /services/azure/streaming.html
          filter:
            platform:
              - Azure
            viewpoints:
              - General
            technologies:
              - Streaming

        - name: Messaging on Azure
          description: On this diagram you can find all the possible options to handle queueing and messaging.
          preview: /services/azure/DTMessaging.png
          items:
            - /services/azure/messagingDT.html
          filter:
            platform:
              - Azure
            viewpoints:
              - General
            technologies:
              - Streaming

        - name: PostgreSQL on Azure
          description: There are multiple options to run PostgreSQL on Azure. Find out more here.
          preview: /services/azure/DTPostgreSQL.png
          items:
            - /services/azure/postgresql.html
          filter:
            platform:
              - Azure
            viewpoints:
              - General
            technologies:
              - PostgreSQL

        - name: Spark on Azure
          description: Spark is an extremely popular technology and we have several options to run in on Azure.
          preview: /services/azure/DTSpark.png
          items:
            - /services/azure/spark.html
          filter:
            platform:
              - Azure
            viewpoints:
              - General
            technologies:
              - Spark

        - name: NoSQL on Azure
          description: This Decisison Tree covers various options for NoSQL on Azure including Cosmos DB.
          preview: /services/azure/DTCosmosDB.png
          items:
            - /services/azure/cosmos.html
          filter:
            platform:
              - Azure
            viewpoints:
              - General
            technologies:
              - NoSQL

        - name: MySQL on Azure
          description: This Decisison Tree covers MySQL and MariaDB options on Azure.
          preview: /services/azure/DTMySQL.png
          items:
            - /services/azure/mysql.html
          filter:
            platform:
              - Azure
            viewpoints:
              - General
            technologies:
              - MySQL

        - name: Caching on Azure
          description: Redis SKUs (including Redis Enterprise)and other caching solutions (Memcached, Cosmos DB) are covered.
          preview: /services/azure/DTRedis.png
          items:
            - /services/azure/redis.html
          filter:
            platform:
              - Azure
            viewpoints:
              - General
            technologies:
              - Caching

        - name: Data Lake on Azure
          description: This diagram answers the question on when to use which Storage for Data Lake deployments on Azure.
          preview: /services/azure/DTStorage.png
          items:
            - /services/azure/storage.html
          filter:
            platform:
              - Azure
            viewpoints:
              - General
            technologies:
              - Data Lake

    - name: Solutions Gallery
      services:
        - name: IoT on Azure
          description: This diagram gives you some basic understanding of designing data-heavy IoT solutions on Azure.
          preview: /services/azure/DTIOT.png
          items:
            - /services/azure/DTIOT.html
          filter:
            platform:
              - Azure
            viewpoints:
              - Industry
            technologies:
              - IoT
              - Time-Series
              
        - name: Modern Data Architecure - Use case
          description: All the Synapse Features and components on on DT.
          preview: /services/azure/DT_Synapse_Components.png
          items:
            - /services/azure/DTSynapse.html
          filter:
            platform:
              - Azure
            viewpoints:
              - Security
              - General
            technologies:
              - Analytics

    - name: Useful Materials
      services:
        - name: How to Select Data Tech on Azure
          link: https://www.linkedin.com/pulse/how-select-proper-data-backend-technology-azure-andrei-zaichikov/
          description: This article explains why and how we have build Albero project.
          preview: /services/materials/howto.jpg
          filter:
            platform:
            - Azure
            viewpoints:
            - General
            technologies:
            - General

        - name: Full List of Azure Public DataSets
          link: https://github.com/albero-azure/albero/blob/main/publicdatasets.md
          description: We are listing all publicly available datasets in Azure.
          preview: /services/materials/lists.png
          filter:
            platform:
            - Azure
            viewpoints:
            - General
            - Migration
            technologies:
            - Analytics

        - name: Crafting Azure Data Architecture
          link: https://www.linkedin.com/pulse/crafting-azure-data-architecture-albero-decision-tree-zaichikov/
          description: Provides you with the method to craft architecture for Azure Data backend.
          preview: /services/materials/crafting.png
          filter:
            platform: 
            - Azure
            - General
            viewpoints:
            - General
            technologies:
            - General

        - name: Azure Synapse Analytics Access Management
          link: https://www.linkedin.com/pulse/simple-access-management-multi-tenant-environment-azure-zaichikov/
          description: Gives you a simple example of access management in multi-tenant env in Synapse Provisioned pool.
          preview: /services/materials/access.png
          filter:
            platform:
            - Azure
            viewpoints:
            - Security
            technologies:
            - General
            - Analytics          

        - name: Azure Storage Access Control Cheat Sheet
          link: https://www.linkedin.com/pulse/azure-data-lake-storage-gen2-access-control-cheat-sheet-zaichikov/
          description: This cheat sheet describes all available options for Azure Storage Authentication.
          preview: /services/materials/storageaccess.jpg
          filter:
            platform:
            - Azure
            viewpoints:
            - Security
            technologies:
            - General
            - Analytics

        - name: Azure Synapse Disaster Recovery
          link: https://www.linkedin.com/pulse/some-notes-azure-synapse-disaster-recovery-andrei-zaichikov/
          description: Some notes on different scenarios for Azure Synapse Analytics failover.
          preview: /services/materials/synapsedr.png
          filter:
            platform:
            - Azure
            viewpoints:
            - Security
            technologies:
            - General
            - Analytics

        - name: Azure Cosmos DB Design Patterns
          link: https://www.linkedin.com/pulse/azure-cosmos-db-design-patterns-andrei-zaichikov/
          description: Here we are discussing most valuable design patterns for Azure Cosmos DB.
          preview: /services/materials/cosmos.png
          filter:
            platform:
            - Azure
            viewpoints:
            - General
            technologies:
            - NoSQL

        - name: Some Tips & Tricks for Oracle to Azure Synapse migrations using SSMA
          link: https://www.linkedin.com/pulse/some-tips-tricks-oracle-azure-synapse-analytics-using-zaichikov/
          description: Here we discuss some best practices for using SSMA for Oracle to Synapse migrations.
          preview: /services/materials/ora2synapse.png
          filter:
            platform:
            - Azure
            viewpoints:
            - General
            - Migration
            technologies:
            - Analytics


