sidebar:
  link:
    home: /
    repo: https://github.com/albero-azure/albero/issues
    share: /
    contact: /


filter:
  platforms:
    - Azure

  technologies:
    - General
    - Caching
    - Data Lake
    - MySQL
    - NoSQL
    - PostgreSQL
    - SQL Server
    - Spark
    - Streaming

  viewpoints:
    - General
    - Security
    - Developer
    - Industry

mainpage:
  groups:
    - name: Azure Services
      services:
        - name: Data Services
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /services/azure/mainDT_0.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
          filter:
            platforms:
              - Platform 2

        - name: Azure Data Services 2
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
          filter:
            technologies:
              - Technology 3

        - name: Azure Data Services 3
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
          filter:
            platforms:
              - Platform 1

        - name: Test Search 1
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Azure Data Services 5
          description: Try search somthing in description
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Azure Data Services 6
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Test Search 2
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
          filter:
            platforms:
              - Platform 1

        - name: Azure Data Services 8
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
          filter:
            platforms:
              - Platform 1

    - name: Favourites 2
      services:
        - name: Azure Data Services 1
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Azure Data Services 2
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Azure Data Services 3
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

    - name: Favourites 3
      services:
        - name: Azure Data Services 1
          link: https://albero.cloud/mainDT_2.png
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Azure Data Services 2
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Azure Data Services 3
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Test Search 3
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
          filter:
            viewpoints:
              - Viewpoint 1
              - Viewpoint 3
            technologies:
              - Technology 3

        - name: Azure Data Services 5
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
