sidebar:
  link:
    home: /
    repo: https://github.com/albero-azure/albero/issues
    share: /
    contact: /


filter:
  platforms:
    - Azure

  technologies:
    - General
    - Caching
    - Data Lake
    - MySQL
    - NoSQL
    - PostgreSQL
    - SQL Server / Database
    - Spark
    - Streaming

  viewpoints:
    - General
    - Security
    - Developer
    - Industry

mainpage:
  groups:
    - name: Main Decision Trees
      services:
        - name: Azure Data Services
          description: This is the main Decision Tree focused on selecting proper data technology on Azure.
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
          filter:
            platforms:
              - Azure
            viewpoints:
              - General
            technologies:
              - General

        - name: Azure Data Programmability
          description: This Decision Tree is focused on languages, file formats, SDKs and limitations of Azure Data Services.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
          filter:
            platforms:
              - Azure
            viewpoints:
              - Developer
            technologies:
              - General

        - name: Azure Data Security
          description: This is a Decision Tree focused on Security aspects, such as Priviliges, Networking and Encryption.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
          filter:
            platforms:
              - Azure
            viewpoints: 
              - Security
            technologies:
              - General

    - name: Technology-Focused Decision Trees
      services:
        - name: SQL Database on Azure
          description: Here you can find the guidance on various service tiers for SQL Database on Azure.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
          filter:
            platform:
              - Azure
            viewpoints:
              - General
            technologies:
              - SQL Server / Database

        - name: Azure Data Services 2
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Azure Data Services 3
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

    - name: Solutions Gallery
      services:
        - name: Azure Data Services 1
          link: https://albero.cloud/mainDT_2.png
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Azure Data Services 2
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Azure Data Services 3
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Test Search 3
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
          filter:
            viewpoints:
              - Viewpoint 1
              - Viewpoint 3
            technologies:
              - Technology 3

        - name: Azure Data Services 5
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

    - name: Useful Materials
      services:
        - name: Azure Data Services 1
          link: https://albero.cloud/mainDT_2.png
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html

        - name: Azure Data Services 2
          description: Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          preview: /common/Legend.png
          items:
            - /services/azure/mainDT_0.html
            - /services/azure/mainDT_1.html
            - /services/azure/mainDT_2.html
